version: '3.9'

services:
  journey_db:
    image: postgres
    container_name: journey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19072004m
      POSTGRES_DB: journeys
    ports:
      - '5432:5432'
    networks:
      - journey-network

  app:
    image: journeyjava
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 19072004m
      DB_NAME: journeys
      DB_HOST: journey_db:5432
    depends_on:
      - journey_db
    networks:
      - journey-network

networks:
  journey-network:
    driver: bridge