app:
  hibernate:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true

#        journey_db:5432